name: iconify_flutter
description: '100+ open source icon sets for flutter to make you app more beautiful'
version: 0.0.3
homepage: 'https://github.com/andronasef/iconify_flutter'

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  colorful_iconify_flutter: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
