name: Build Package
on: workflow_dispatch
jobs:
  Building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm i && flutter pub get
      - name: Building Icons
        run: node generator/gen.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated Update of Flutter Icons'
