name: Making Website
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: website

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm i

      - name: Building Website
        run: npm run build

      - name: Make 404
        run: cp ./website/dist/index.html ./website/dist/404.html

      - name: Publishing Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
